### PR TITLE
List to prereqs 

### PR DESCRIPTION
**Pull request by YuxiangDi**
`list_to_bool/2` done. It reads a list of list course which created by parsePrereq.pl
example: 

```
?- list_to_bool([['CSE 12'],['CSE 11','or','CSE 8B'],['CSE 15L']],X).
X = bool(and(and(val(id('CSE', '15L')), or(val(id('CSE', '8B')), val(id('CSE', '11')))), val(id('CSE', '12')))).
```

preocess expression by `boolprereqs_to_list/2`:

```
?- prereq_proc: boolprereqs_to_list(and(and(val(id('CSE', '15L')), or(val(id('CSE', '8B')), val(id('CSE', '11')))), val(id('CSE', '12'))),X,[]).
X = ['CSE 15L', 'CSE 8B', 'CSE 12'] ;
X = ['CSE 15L', 'CSE 11', 'CSE 12'].
```

### CODE REVIEW

**Comment by EccentricBarad** [comment]
Oh so you want it in this format -> [['CSE 12'],['CSE 11','or','CSE 8B'],['CSE 15L']]

It is right no in this format, which seems to be more intuitive to read.

['CSE 12',[['CSE 11','or','CSE 8B'],['CSE 15L']]]

**Comment by YuxiangDi** [comment]
I see, the list is used as a pair to store AND. Is that possible to store in my original format?
I tryed to modify my code and it seems hard to decide when does the and list comes and when does the or list comes with a list that has unknow level of nested list inside.
let me know if it's also very hard for you to modify the list format. It's still doable for me to change the list parser.

**Comment by EccentricBarad** [comment]
How about that?

[['CSE 12',[['CSE 11','or','CSE 8B'],['CSE 15L']]], ['CSE 30',[['CSE 12','or','CSE 15L'],['CSE 21']]]]

or 

[[['CSE 12'],[['CSE 11','or','CSE 8B'],['CSE 15L']]], [['CSE 30'],[['CSE 12','or','CSE 15L'],['CSE 21']]]]

**Comment by YuxiangDi** [comment]
Actually,your original one is easier:
['CSE 12',[['CSE 11','or','CSE 8B'],['CSE 15L']]]

Let me try that first. I will let you if I cann't parser it.

**Comment by borisvassilev** [comment]
Hello guys, some comments:

This is easiest to generate from the HTML using `xpath` and `findall`: `[['CSE 12'],['CSE 11','or','CSE 8B'],['CSE 15L']]`.

Here, the `or` in between is not strictly necessary, if you know for sure that you always have a list `[A, B, C]` that should be interpreted as "A and B and C", where the elements of the list can be lists like `B = [X, Y, Z]` that should be interpreted as "X or Y or Z". You should however make sure that there is an `or` between each two things while scraping the data from the website!

This is the most general form as a boolean: `and('CSE 12', and(or('CSE 11','CSE 8B'), 'CSE 15L'))`

My suggestion would be keep it as it was initially. From what I see Justin already had it working? But at the end it is your decision.

**Comment by EccentricBarad** [comment]
We decided to have them hardcoded at three different stages. One for
Justin, one for Sean and one for me. And we were running under the
assumption that each stage is implemented, so that we do not slow each
other down. Now that they all are, it will be easier to combine them and
flush the design.

In my comment on Slack, when we were planning how to split, I provided the
format that my part will be outputting. I placed the class id at the
beginning so that you can differentiate which class the prereqs in the list
are for.

On Fri, Feb 27, 2015 at 11:35 PM, Boris notifications@github.com wrote:

> Hello guys, some comments:
> 
> This is easiest to generate from the HTML using xpath and findall: [['CSE
> 12'],['CSE 11','or','CSE 8B'],['CSE 15L']].
> 
> Here, the or in between is not strictly necessary, if you know for sure
> that you always have a list [A, B, C] that should be interpreted as "A
> and B and C", where the elements of the list can be lists like B = [X, Y,
> Z] that should be interpreted as "X or Y or Z". You should however make
> sure that there is an or between each two things while scraping the data
> from the website!
> 
> This is the most general form as a boolean: and('CSE 12', and(or('CSE
> 11','CSE 8B'), 'CSE 15L'))
> 
> My suggestion would be keep it as it was initially. From what I see
> Justing already had it working? But at the end it is your decision.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/StanfordOSAcademySWIProlog/contentteam/pull/3#issuecomment-76515547
> .

## 

Kristiyan H. Dzhamalov

**Pull request merged**
